---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: openstack-api-backup
  namespace: openstack-api-backup
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openstack-api-backup
  data:
    - secretKey: aws_credentials
      remoteRef:
        key: accounts/holecs
        property: awscli_credentials
    - secretKey: backup_rotate
      remoteRef:
        key: openstack-api-backup/config
        property: backup_rotate
    - secretKey: s3_endpoint
      remoteRef:
        key: openstack-api-backup/config
        property: s3_endpoint
    - secretKey: s3_bucket_uri
      remoteRef:
        key: openstack-api-backup/config
        property: s3_bucket_uri
    - secretKey: os_auth_url
      remoteRef:
        key: openstack-api-backup/config
        property: os_auth_url
    - secretKey: os_application_credential_id
      remoteRef:
        key: openstack-api-backup/config
        property: os_application_credential_id
    - secretKey: os_application_credential_secret
      remoteRef:
        key: openstack-api-backup/config
        property: os_application_credential_secret
