---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: openstack-api-backup
  namespace: openstack-api-backup
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
          containers:
            - name: openstack-api-backup
              image: ghcr.io/nerc-project/openstack-api-backup:main
              imagePullPolicy: Always
              env:
                - name: HOME
                  value: '/tmp'
                - name: S3_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: openstack-api-backup
                      key: s3_endpoint
                - name: S3_BUCKET_URI
                  valueFrom:
                    configMapKeyRef:
                      name: openstack-api-backup
                      key: s3_bucket_uri
                - name: BACKUP_ROTATE
                  valueFrom:
                    configMapKeyRef:
                      name: openstack-api-backup
                      key: backup_rotate
                - name: BACKUP_DIR
                  value: '/backups'
                - name: AWSCLI_CREDS
                  value: '/tmp/.aws/credentials'
              volumeMounts:
                - name: openstack-api-backup
                  mountPath: "/backups"
                - name: openstack-api-backup-awscli-creds
                  mountPath: "/tmp/.aws/credentials"
                  subPath: 'credentials'
          volumes:
            - name: openstack-api-backup
              persistentVolumeClaim:
                claimName: openstack-api-backup
            - name: openstack-api-backup-awscli-creds
              secret:
                secretName: openstack-api-backup
                items:
                  - key: 'aws_credentials'
                    path: 'credentials'
                defaultMode: 0400
